@startuml
'START DTO SECTION'
struct NodeDto {
  +NodeId id
  +{static} &str kind
  +{static} &str name
  +{field} (f32, f32) position
  +{field} String name_override
}

struct InputFieldDto {
  +&str name
  +&str data_type
}

struct OutputPinDto {
  +&str name
  +&str data_type
}

enum DataValueDto {
  +{field} Number(f64)
  +{field} Boolean(bool)
  +{field} Color(Color)
  +{field} Vector3(Vec3)
  +{field} Point3(Point3)
}

struct ConnectionDto {
  +NodeId from_node
  +usize from_index
  +NodeId to_node
  +usize to_index
}

struct GraphDto {
  +usize id
}

enum InputConstraints {
  NUMBER { f64 min, f64 max }
  BOOLEAN
  COLOR
  ...
}

GraphDto *--"0..*" NodeDto
GraphDto *--"0..*" ConnectionDto
NodeDto *--"0..*" InputFieldDto
NodeDto *--"0..*" OutputPinDto
InputFieldDto *-- DataValueDto
InputFieldDto *-- InputConstraints
OutputPinDto *-- DataValueDto
'END DTO SECTION'
@enduml